import 'dart:io';
import 'package:dio/dio.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../core/constants/api_constants.dart';
import 'token_service.dart';

/// Downloads the police recovery report PDF (JWT-authenticated) and opens the
/// system share sheet so the owner can save it or send it to the police.
class ReportService {
  final Dio _dio = Dio(BaseOptions(validateStatus: (s) => true));

  /// Downloads the recovery PDF and opens the share sheet.
  /// If [captureFresh] is true, the backend will first ask the agent to take
  /// a brand-new webcam shot + screenshot and wait for them to arrive, so the
  /// PDF contains images from "right now" rather than old test captures. This
  /// call can take 25-30 seconds in that mode — the UI should show progress.
  Future<void> downloadAndShare(String deviceId, String deviceName,
      {bool captureFresh = false}) async {
    final token = await TokenService().getToken();
    final url = '${ApiConstants.baseUrl}/api/device/$deviceId/report'
        '${captureFresh ? "?capture_fresh=1" : ""}';
    final resp = await _dio.get(
      url,
      options: Options(
        responseType: ResponseType.bytes,
        headers: {'Authorization': 'Bearer $token'},
        // Fresh capture waits ~25s server-side; give it headroom.
        receiveTimeout: Duration(seconds: captureFresh ? 60 : 30),
      ),
    );
    if (resp.statusCode != 200) {
      throw Exception('Report failed (${resp.statusCode})');
    }
    final dir = await getTemporaryDirectory();
    final safeName = deviceName.replaceAll(RegExp(r'[^A-Za-z0-9_-]'), '_');
    final file = File('${dir.path}/PhantomTrace_Report_$safeName.pdf');
    await file.writeAsBytes(resp.data as List<int>);
    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/pdf')],
      subject: 'PhantomTrace Recovery Report — $deviceName',
      text: 'Device recovery report generated by PhantomTrace.',
    );
  }
}
