import 'dart:io';
import 'package:dio/dio.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../core/constants/api_constants.dart';
import 'token_service.dart';

/// Downloads the police recovery report PDF (JWT-authenticated) and opens the
/// system share sheet so the owner can save it or send it to the police.
class ReportService {
  final Dio _dio = Dio(BaseOptions(validateStatus: (s) => true));

  Future<void> downloadAndShare(String deviceId, String deviceName) async {
    final token = await TokenService().getToken();
    final resp = await _dio.get(
      '${ApiConstants.baseUrl}/api/device/$deviceId/report',
      options: Options(
        responseType: ResponseType.bytes,
        headers: {'Authorization': 'Bearer $token'},
      ),
    );
    if (resp.statusCode != 200) {
      throw Exception('Report failed (${resp.statusCode})');
    }
    final dir = await getTemporaryDirectory();
    final safeName = deviceName.replaceAll(RegExp(r'[^A-Za-z0-9_-]'), '_');
    final file = File('${dir.path}/PhantomTrace_Report_$safeName.pdf');
    await file.writeAsBytes(resp.data as List<int>);
    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/pdf')],
      subject: 'PhantomTrace Recovery Report — $deviceName',
      text: 'Device recovery report generated by PhantomTrace.',
    );
  }
}
